### ISSUE TITLE
citrix_daas_machine_catalog in AWS requires properties not applicable

### ISSUE THREAD

**Issue by SLemonier** [citrix/terraform-provider-citrix#16]
Hello,

When you try to create a machine catalog in AWS, it failed, requiring two properties "storage_type" and "use_managed_disks" not applicable.

Error Message:
```
on machine_catalog.tf line 9, in resource "citrix_daas_machine_catalog" "AAA-TF":
│    9:     provisioning_scheme         =   {
│   10:         machine_config = {
│   11:             hypervisor = citrix_daas_hypervisor.NPRD-EUC-TF.id
│   12:             hypervisor_resource_pool = citrix_daas_hypervisor_resource_pool.NPRD-EUC-1A-TF.id
│   13:             service_offering = "M6i Extra Large Instance"
│   14:             image_id = "ami-09c9fcf1bd691b228"
│   15:             #machine_profile = ""
│   16:         }
│   17:         network_mapping = {
│   18:             network_device = "0"
│   19:             network = citrix_daas_hypervisor_resource_pool.NPRD-EUC-1A-TF.subnets[0]
│   20:         }
│   21:         number_of_total_machines =  1
│   22:         machine_account_creation_rules ={
│   23:             naming_scheme =     "NAME#####"
│   24:             naming_scheme_type ="Numeric"
│   25:             domain =            "mydomain.local"
│   26:             domain_ou =         "OU=Citrix Servers,DC=mydomain,DC=local"
│   27:         }
│   28:     }
│ 
│ Inappropriate value for attribute "provisioning_scheme": attributes "storage_type" and "use_managed_disks"
│ are required.
```

These properties should not be required, or at least not with an AWS hypervisor.

Thanks in advance for your work,
Steven

**Comment by zhuolun-liu-citrix** [comment]
Hi @SLemonier a fix for this issue has been release in version v0.3.3. Thank you!

**Comment by SLemonier** [comment]
Hello @zhuolun-liu-citrix 

I gave it a try, now it failed with:

citrix_daas_machine_catalog.AAA-TF: Creating...
│ Error: Error creating Machine Catalog
│ 
│   with citrix_daas_machine_catalog.AAA-TF,
│   on machine_catalog.tf line 1, in resource "citrix_daas_machine_catalog" "AAA-TF":
│    1: resource "citrix_daas_machine_catalog" "AAA-TF" {
│ 
│ TransactionId: 49c9f869-eb5f-4509-938e-cf134c459204
│ Error message: The required parameter is not specified.
│ Parameter name: MasterImagePath

I don't think we should specify a _MasterImagePath_ as for AWS, it takes the AMI and construct the Path based on Hypervisor Resource Pool.

**Comment by zhuolun-liu-citrix** [comment]
Hi @SLemonier . The error was passed through from our API, which means that the provider failed to resolve the master image path according to what's available in TF. Can you please make sure that both `citrix_daas_machine_catalog.provisioning_scheme.machine_config.master_image` and `citrix_daas_machine_catalog.provisioning_scheme.machine_config.image_ami` are specified for the AWS catalog?

`citrix_daas_machine_catalog.provisioning_scheme.machine_config.master_image` should be the image name on AWS.
`citrix_daas_machine_catalog.provisioning_scheme.machine_config.image_ami` should be the ami of the image.

I totally agree that the error of not being able to resolve master image path should have a better error message. We will work on that.

Thank you!

**Comment by SLemonier** [comment]
Hi @zhuolun-liu-citrix, I've added master_image but still got the same error:

```
Error: Error creating Machine Catalog

  with citrix_daas_machine_catalog.AAA-TF,
  on machine_catalog.tf line 1, in resource "citrix_daas_machine_catalog" "AAA-TF":
   1: resource "citrix_daas_machine_catalog" "AAA-TF" {

TransactionId: add301e3-a899-43ea-b216-01c4a7543d36
Error message: The required parameter is not specified.
Parameter name: MasterImagePath
```

**Comment by zhuolun-liu-citrix** [comment]
Hi @SLemonier . Please Add both `master_image` and `image_ami` to your terraform.

**Comment by SLemonier** [comment]
They are both added already:

<img width="328" alt="Screenshot 2023-11-20 at 17 55 36" src="https://github.com/citrix/terraform-provider-citrix/assets/20860016/41915919-2db0-442e-8943-aa5dbc66b1cc">

**Comment by zhuolun-liu-citrix** [comment]
Please refer to https://registry.terraform.io/providers/citrix/citrix/latest/docs/resources/daas_machine_catalog#image_ami

In provisioning_scheme, we do not have an `image_id` field. Instead, we have `image_ami` for specifying the image AMI on AWS. Please try changing `image_id` to `image_ami`. 

Thank you.

**Comment by SLemonier** [comment]
Oh my bad. I've corrected it.

The machine catalog eventually failed:

`Create Catalog failed with an unknown reason, see terminating error for more details.
Stack Trace:
   at Citrix.Orchestration.Base.PowerShellSdk.ProvisioningSchemeService.BackgroundTasks.ProvisioningSchemeTask.ThrowOnTerminatingError(SdkProvisioningSchemeAction sdkProvisioningSchemeAction)
   at Citrix.Orchestration.Base.PowerShellSdk.ProvisioningSchemeService.BackgroundTasks.ProvisioningSchemeTask.WaitForProvisioningSchemeActionCompletion(Guid taskId, Action`1 actionResultsObtained)
   at Citrix.Orchestration.Base.PowerShellSdk.ProvisioningSchemeService.BackgroundTasks.ProvisioningSchemeCreationTask.StartProvisioningAction()
   at Citrix.Orchestration.Base.PowerShellSdk.ProvisioningSchemeService.BackgroundTasks.ProvisioningSchemeCreationTask.RunTask()
   at Citrix.Orchestration.Base.PowerShellSdk.BackgroundTaskService.BackgroundTask.Task.Run()

StudioErrorId : ProvisioningTaskError
ErrorCategory : NotSpecified
TaskState : UnknownError
TaskStateInformation : Terminated
ErrorId : ManagedMachineGeneralException
Operation : PreparingMasterImage
ErrorMessage : Timed out waiting for: Volume for instance i-07e871ff626bc7ba3

`

**Comment by SLemonier** [comment]
@zhuolun-citrix it's Citrix Cloud Customer.

CID = 5eos1vtp7w84
Job ID = 1938bdf9-3f41-4dde-aa8e-fc55895e661b

**Comment by zhuolun-citrix** [comment]
Hi @SLemonier,

Can you please try to create a machine catalog in WebStudio UI with the same image and SKU and see if you can reproduce the issue? We are trying to triage the error your had but we have very little info to work with. Please try to create a catalog on UI and try another one via Terraform, and share the TransactionId and JobId regardless of the result.

Thank you!

**Comment by SLemonier** [comment]
Hello @zhuolun-citrix 

I managed to identify the issue by trying to manually create a machine catalog. A co-worker changed the API key and secrets.
The machine catalog creation is successful, but it is not able to create a machine.

The security-group is missing:
![Screenshot 2023-12-07 at 12 52 29](https://github.com/citrix/terraform-provider-citrix/assets/20860016/12524fe8-9b5a-4571-ade2-b01607cd6bc4)

I think you should add the support for this.

**Comment by zhuolun-citrix** [comment]
Thanks for the update @SLemonier ,

Yes, this seems to be an issue for AWS EC2 catalog. We will look into this further.

**Comment by SLemonier** [comment]
Hello @zhuolun-citrix, 
I wish you a happy new year!

Do you have any update on this to share please?

**Comment by zhuolun-citrix** [comment]
Hi @SLemonier ,

AWS machine catalog support is on our roadmap. We are still working on it at the moment.

Thank you!

**Comment by zhuolun-citrix** [comment]
Hi @SLemonier ,

AWS EC2 MCS provisioning is now supported in the latest release v0.5.2 #43 .

Please try it out with the new provider version.

Thank you!
