### ISSUE TITLE
StorageType 'Azure_Ephemeral_OS_Disk' is invalid

### ISSUE THREAD

**Issue by j7lloyd** [citrix/terraform-provider-citrix#62]
When attempting to create a machine catalog with a provisioning scheme using an ephemeral OS disk, it fails as follows:

```
2024-04-24T10:04:17.386+0100 [ERROR] provider.terraform-provider-citrix_v0.5.5: Response contains error diagnostic:
  diagnostic_detail=
  | TransactionId: f3365277-c4e3-429f-bb91-629b4fbbbf84
  | JobId: f184f5f2-b8ac-4fd4-83c0-614cc72ad66f
  | Error message: Failure result exists during validating provisioning scheme creation.
   tf_req_id=18293840-229b-970c-6a72-d28efbc43b8c tf_resource_type=citrix_machine_catalog @caller=github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/diag/diagnostics.go:58 @module=sdk.proto diagnostic_severity=ERROR diagnostic_summary="Error creating Machine Catalog" tf_proto_version=6.4 tf_provider_addr=registry.terraform.io/citrix/citrix tf_rpc=ApplyResourceChange timestamp="2024-04-24T10:04:17.386+0100"
2024-04-24T10:04:17.390+0100 [ERROR] vertex "citrix_machine_catalog.MC09-AVDdaasCMP-009" error: Error creating Machine Catalog
╷
│ Error: Error creating Machine Catalog
│
│   with citrix_machine_catalog.MC09-AVDdaasCMP-009,
│   on catalogs.tf line 1, in resource "citrix_machine_catalog" "MC09-AVDdaasCMP-009":
│    1: resource "citrix_machine_catalog" "MC09-AVDdaasCMP-009" {
│
│ TransactionId: f3365277-c4e3-429f-bb91-629b4fbbbf84
│ JobId: f184f5f2-b8ac-4fd4-83c0-614cc72ad66f
│ Error message: Failure result exists during validating provisioning scheme creation.
```

Upon checking the error details in Citrix DaaS, under Manage, it implies the StorageType is invalid:

```
Failure result exists during validating provisioning scheme creation.
Stack Trace:
   at Citrix.Orchestration.Base.PowerShellSdk.ProvisioningSchemeService.BackgroundTasks.ProvisioningSchemeTask.ThrowOnTerminatingError(SdkProvisioningSchemeAction sdkProvisioningSchemeAction)
   at Citrix.Orchestration.Base.PowerShellSdk.ProvisioningSchemeService.BackgroundTasks.ProvisioningSchemeTask.WaitForProvisioningSchemeActionCompletion(Guid taskId, Action`1 actionResultsObtained)
   at Citrix.Orchestration.Base.PowerShellSdk.ProvisioningSchemeService.BackgroundTasks.ProvisioningSchemeCreationTask.StartProvisioningAction()
   at Citrix.Orchestration.Base.PowerShellSdk.ProvisioningSchemeService.BackgroundTasks.ProvisioningSchemeCreationTask.RunTask()
   at Citrix.Orchestration.Base.PowerShellSdk.BackgroundTaskService.BackgroundTask.Task.Run()

StudioErrorId : ProvisioningTaskError
ErrorCategory : NotSpecified
TaskState : ValidationFailure
TaskStateInformation : Terminated
ErrorId : ValidationFailure
Operation : ValidatingInputs
ErrorMessage : Error: The following custom properties have invalid storage type values: 'StorageType'
```

From my experience and limited testing using the code I shared in PR (#45), the custom property `UseEphemeralOsDisk` is required to provision ephemeral OS disks, as described here: https://docs.citrix.com/en-us/citrix-daas/install-configure/machine-catalogs-create/create-machine-catalog-citrix-azure.html#create-a-machine-catalog-with-an-azure-ephemeral-disk

**Comment by j7lloyd** [comment]
I had hoped to work around this by setting `storage_type = "Standard_LRS"` and using the new `custom_properties` argument, as follows, to provision ephemeral OS disks:

```
custom_properties = [
  {
    name  = "UseEphemeralOsDisk"
    value = "true"
  }
]
```

However, that failed too, unfortunately 😞

```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to citrix_machine_catalog.MC09-AVDdaasCMP-009, provider
│ "provider[\"registry.terraform.io/citrix/citrix\"]" produced an unexpected new value: .provisioning_scheme: inconsistent  
│ values for sensitive attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by aneeshk-citrix** [comment]
Thanks @j7lloyd for pointing this out. We will work on a fix for this.

Aneesh
